### ISSUE TITLE
Unpickling traceback crashes on Python 3.8.

### ISSUE THREAD

**Issue by felixxm** [ionelmc/python-tblib#46]
`CodeType` signature was changed in Python 3.8 (see [issue36886](https://bugs.python.org/issue36886)). Please find below traceback from the Django's test suite:

```
======================================================================
ERROR: test_add_failing_subtests (test_runner.test_parallel.RemoteTestResultTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/felixx/repo/django/tests/test_runner/test_parallel.py", line 75, in test_add_failing_subtests
    subtest_test.run(result=result)
  File "/usr/local/lib/python3.8/unittest/case.py", line 679, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "/usr/local/lib/python3.8/unittest/case.py", line 592, in _feedErrorsToResult
    result.addSubTest(test.test_case, test, exc_info)
  File "/home/felixx/repo/django/django/test/runner.py", line 238, in addSubTest
    self.check_picklable(test, err)
  File "/home/felixx/repo/django/django/test/runner.py", line 156, in check_picklable
    self._confirm_picklable(err)
  File "/home/felixx/repo/django/django/test/runner.py", line 130, in _confirm_picklable
    pickle.loads(pickle.dumps(obj))
  File "/home/felixx/.virtualenvs/django-test-3.8/lib/python3.8/site-packages/tblib/pickling_support.py", line 16, in unpickle_traceback
    return ret.as_traceback()
  File "/home/felixx/.virtualenvs/django-test-3.8/lib/python3.8/site-packages/tblib/__init__.py", line 99, in as_traceback
    code = CodeType(
TypeError: an integer is required (got type bytes)
```

**Comment by felixxm** [comment]
OK it looks that it's already fixed per f6e191af71a98620961e8e9bfefea2cb3dbb8534. Can we ask for a new release?

**Comment by ionelmc** [comment]
Ah whoops looks like I forgot to release.

**Comment by ionelmc** [comment]
1.5.0 out now.

**Comment by felixxm** [comment]
Thanks :rocket:
