### ISSUE TITLE
incompatibility with concurrent.futures 

### ISSUE THREAD

**Issue by nmaxwell** [ionelmc/python-tblib#62]
using `tblib.pickling_support.install()` causes an exception when using `concurrent.futures.ProcessPoolExecutor`. Here is a minimal example:

```
from concurrent.futures import ProcessPoolExecutor

import tblib.pickling_support

tblib.pickling_support.install()


def foo(x):
    if x > 2:
        raise RuntimeError('bar')


if __name__ == "__main__":
    with ProcessPoolExecutor(max_workers=2) as executor:

        try:
            list(
                executor.map(foo, range(50))
            )
        except Exception as ex:
            print('exception: ', ex)

    print(' --- done --- ')

```

I get an exception when the atexit functions run, this is the output:

```
exception:  bar
 --- done --- 
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/nick/lego-root/lib/python3.7/concurrent/futures/process.py", line 102, in _python_exit
    thread_wakeup.wakeup()
  File "/home/nick/lego-root/lib/python3.7/concurrent/futures/process.py", line 90, in wakeup
    self._writer.send_bytes(b"")
  File "/home/nick/lego-root/lib/python3.7/multiprocessing/connection.py", line 183, in send_bytes
    self._check_closed()
  File "/home/nick/lego-root/lib/python3.7/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed

Process finished with exit code 0
```

commenting out ```tblib.pickling_support.install()``` solves the problem, I then get the expected output with no exceptions:

```
exception:  bar
 --- done --- 

Process finished with exit code 0
```

**Comment by ionelmc** [comment]
This doesn't reproduce on my python 3.7.8 (fedora). I suspect it's a python bug and you can reproduce it without tblib if you have more runs.

**Comment by nmaxwell** [comment]
Hey thanks for the follow up.

So it reproduces on Python 3.8.2 (Ubuntu 20.04). I see you mentioned running on Fedora, I wonder if that could influence it. Below is a Docker example that reproduces on Ubuntu. I'll try Fedora also.

See this docker file [Dockerfile.txt](https://github.com/ionelmc/python-tblib/files/5213527/Dockerfile.txt) (you'll have to rename from Dockerfile.txt to Dockerfile, github won't me let upload otherwise)

to build it: `docker build -t map_bug .`

to run it, without installing pickling support, to show the **expected output:**   `docker run -it map_bug python3 test.py`

output:

```
exception:  bar
 --- done --- 
```

to run it, with picking support, to show **the error:**  `docker run -it map_bug python3 test.py bug`

output:

```
install pickling support
exception:  bar
 --- done --- 
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 102, in _python_exit
    thread_wakeup.wakeup()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 90, in wakeup
    self._writer.send_bytes(b"")
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 183, in send_bytes
    self._check_closed()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed

```

**Comment by ionelmc** [comment]
Well I've looked at it, it does reproduces and I have no clue what that _python_exit code is for. 

Possibly related issues:
* https://bugs.python.org/issue36281 
* https://bugs.python.org/issue36780

Either way, this seems like a benign problem. Contrast that to what happens if you register signal handlers (it deadlocks - https://bugs.python.org/issue29759).
